# Generated by Django 2.0.2 on 2018-03-17 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('R', 'View'), ('W', 'Edit')], default='R', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_history', to='manager.Document')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_performer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
