# Generated by Django 2.0.2 on 2018-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operation',
            field=models.CharField(choices=[('c', 'Create'), ('m', 'Modify')], default='c', max_length=10),
        ),
    ]
