# Generated by Django 2.0.2 on 2018-03-18 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180317_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_subject', to='manager.Subject'),
        ),
        migrations.AlterField(
            model_name='history',
            name='operation',
            field=models.CharField(choices=[('c', 'Create'), ('m', 'Modify'), ('s', 'Subscribe')], default='c', max_length=10),
        ),
    ]
